version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.20.1
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: 24c085e9876ff890ca4cb715cc2dda092efeea48
        databases:
          default:
            connector: postgres
            host: ec2-54-235-244-22.compute-1.amazonaws.com
            port: '5432'
            database: d2dst4tvhivt6m
            ssl: true
            user: vacktvdutxsvbf
            password: a9fe4ba09b0acb767bc389f4be0f8b4ea1c44591a37db9acc0f282e41ce1e4f5
            migrations: true